// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mvc01.Data;

namespace Mvc01.Migrations
{
    [DbContext(typeof(AppDb))]
    partial class AppDbModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Mvc01.Models.Machine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AcceptableCoins")
                        .HasMaxLength(50);

                    b.Property<bool>("IsLidOpen");

                    b.Property<bool>("IsOn");

                    b.Property<decimal>("TotalAmount");

                    b.Property<decimal>("TotalSellAmount");

                    b.HasKey("Id");

                    b.ToTable("Machines");
                });

            modelBuilder.Entity("Mvc01.Models.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("People");
                });

            modelBuilder.Entity("Mvc01.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateDate");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<decimal>("Price")
                        .HasColumnName("Price")
                        .HasColumnType("decimal(18, 4)");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Mvc01.Models.ProductPicture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<int?>("ProductId");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(512);

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductPictures");
                });

            modelBuilder.Entity("Mvc01.Models.Slot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("MachineId");

                    b.Property<int?>("ProductId");

                    b.Property<int>("Quantity");

                    b.Property<bool>("SellAble");

                    b.HasKey("Id");

                    b.HasIndex("MachineId");

                    b.HasIndex("ProductId");

                    b.ToTable("Slot");
                });

            modelBuilder.Entity("Mvc01.Models.Person", b =>
                {
                    b.OwnsOne("Mvc01.Models.Address", "Home", b1 =>
                        {
                            b1.Property<Guid>("PersonId");

                            b1.Property<string>("Line1");

                            b1.Property<string>("Line2");

                            b1.Property<string>("Line3");

                            b1.Property<string>("PostalCode");

                            b1.Property<string>("Province");

                            b1.HasKey("PersonId");

                            b1.ToTable("People");

                            b1.HasOne("Mvc01.Models.Person")
                                .WithOne("Home")
                                .HasForeignKey("Mvc01.Models.Address", "PersonId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("Mvc01.Models.Address", "Office", b1 =>
                        {
                            b1.Property<Guid>("PersonId");

                            b1.Property<string>("Line1");

                            b1.Property<string>("Line2");

                            b1.Property<string>("Line3");

                            b1.Property<string>("PostalCode");

                            b1.Property<string>("Province");

                            b1.HasKey("PersonId");

                            b1.ToTable("People");

                            b1.HasOne("Mvc01.Models.Person")
                                .WithOne("Office")
                                .HasForeignKey("Mvc01.Models.Address", "PersonId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });

            modelBuilder.Entity("Mvc01.Models.ProductPicture", b =>
                {
                    b.HasOne("Mvc01.Models.Product")
                        .WithMany("Pictures")
                        .HasForeignKey("ProductId");
                });

            modelBuilder.Entity("Mvc01.Models.Slot", b =>
                {
                    b.HasOne("Mvc01.Models.Machine")
                        .WithMany("Slots")
                        .HasForeignKey("MachineId");

                    b.HasOne("Mvc01.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId");
                });
#pragma warning restore 612, 618
        }
    }
}
