// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mvc01.Data;

namespace Mvc01.Migrations
{
    [DbContext(typeof(AppDb))]
    [Migration("20190526030408_update07")]
    partial class update07
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Mvc01.Models.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("People");
                });

            modelBuilder.Entity("Mvc01.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateDate");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<decimal>("Price")
                        .HasColumnName("Price")
                        .HasColumnType("decimal(18, 4)");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Mvc01.Models.Person", b =>
                {
                    b.OwnsOne("Mvc01.Models.Address", "Home", b1 =>
                        {
                            b1.Property<Guid>("PersonId");

                            b1.Property<string>("Line1");

                            b1.Property<string>("Line2");

                            b1.Property<string>("Line3");

                            b1.Property<string>("PostalCode");

                            b1.Property<string>("Province");

                            b1.HasKey("PersonId");

                            b1.ToTable("People");

                            b1.HasOne("Mvc01.Models.Person")
                                .WithOne("Home")
                                .HasForeignKey("Mvc01.Models.Address", "PersonId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("Mvc01.Models.Address", "Office", b1 =>
                        {
                            b1.Property<Guid>("PersonId");

                            b1.Property<string>("Line1");

                            b1.Property<string>("Line2");

                            b1.Property<string>("Line3");

                            b1.Property<string>("PostalCode");

                            b1.Property<string>("Province");

                            b1.HasKey("PersonId");

                            b1.ToTable("People");

                            b1.HasOne("Mvc01.Models.Person")
                                .WithOne("Office")
                                .HasForeignKey("Mvc01.Models.Address", "PersonId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
